### PR TITLE
Handle problems with mixed file endings. Test case SEPTA GTFS feed.

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by perkinsms** [comment]
I no longer maintain this software

Michael

**Comment by fulldecent** [comment]
Hello Michael, thanks for the information. This project is still of great use. Would you be interested to transfer this repository to @xtab or myself to continue maintaining this project? https://help.github.com/articles/how-to-transfer-a-repository

Thank you, Will

**Comment by perkinsms** [comment]
I'll try to figure out how to do that. Glad you enjoy it.

On 8/25/14, William Entriken notifications@github.com wrote:

> Hello Michael, thanks for the information. This project is still of great
> use. Would you be interested to transfer this repository to @xtab or myself
> to continue maintaining this project?
> https://help.github.com/articles/how-to-transfer-a-repository
> 
> Thank you, Will
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/perkinsms/Perl-GTFS/pull/1#issuecomment-53269349

## 

Michael

**Comment by fulldecent** [comment]
Hello, I spoke with GitHub they said if you email them ("Contact") at bottom of page then they will do this for you.

**Comment by perkinsms** [comment]
I sent something to add you as collaborators, would that suffice?

On 10/13/14, William Entriken notifications@github.com wrote:

> Hello, I spoke with GitHub they said if you email them ("Contact") at bottom
> of page then they will do this for you.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/perkinsms/Perl-GTFS/pull/1#issuecomment-58934829

## 

Michael

**Comment by fulldecent** [comment]
Yes, that is great, thank you

**Comment by perkinsms** [comment]
They replied and said they couldn't do it. Maybe I'll try from home
where I have a browser more recent than IE8.0

On 10/14/14, William Entriken notifications@github.com wrote:

> Yes, that is great, thank you
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/perkinsms/Perl-GTFS/pull/1#issuecomment-59107654

## 

Michael

**Comment by fulldecent** [comment]
This PR still works.

But I'm closing the PR because I don't think it will be implemented.

I have stopped using the software and instead wrote a simple SQL script that directly loads GTFS into a SQLite database.

Reference is https://github.com/fulldecent/septa-regionalrail-otp if anyone is interested.

**Pull request closed without merging**
